# Generated by Django 3.2 on 2021-04-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210419_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='dislikes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
