# Generated by Django 3.2 on 2021-04-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210419_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='likes',
        ),
    ]
