# Generated by Django 3.2 on 2021-04-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210419_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='dislikes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
