# Generated by Django 3.2 on 2021-04-19 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210419_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.rating'),
        ),
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.rating'),
        ),
    ]
