# Generated by Django 3.2 on 2021-04-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_id',
            field=models.IntegerField(default=0),
        ),
    ]
