# Generated by Django 3.2 on 2021-04-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rating_rating_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_id', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name': 'Рейтинг ответов',
                'verbose_name_plural': 'Рейтинг ответов',
            },
        ),
        migrations.CreateModel(
            name='RatingQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_id', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name': 'Рейтинг вопросов',
                'verbose_name_plural': 'Рейтинг вопросов',
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='rating',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.ratinganswers'),
        ),
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.ratingquestions'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
