# Generated by Django 3.2 on 2021-06-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
    ]
