# Generated by Django 3.2 on 2021-06-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_answer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='cat-smart.jpg', upload_to='uploads/'),
        ),
    ]
